### ISSUE TITLE
リポジトリをクローンして初回起動時にエラーが発生する

### ISSUE THREAD

**Issue by tecsoc** [imaimai17468/imaimai-whitespace#1]
リポジトリをクローンして初めて起動した時にエラーが発生しました。
リロードしたらなおって、それ以降は発生しなかったです。
もう一度リポジトリをクローンしなおしたら、再現しました。
でもリロードしたらもう出ないです。

直せそうだったら自分でなおします

![image](https://github.com/imaimai17468/imaimai-whitespace/assets/25559838/66399ea0-dc67-4c74-84ec-a37f168e1ff0)

## 環境
bun 1.0.6

**Comment by tecsoc** [comment]
なんとなく原因分かりそうなので一旦トライしてみます。そしてあとでPRつくります

**Comment by tecsoc** [comment]
記事をよく読んだら既知の問題でした
https://zenn.dev/imaimai17468/articles/af22e695ed24a8#%E3%82%A8%E3%83%A9%E3%83%BC%E7%99%BA%E7%94%9F

**Comment by imaimai17468** [comment]
BlockNoteの対応を待ちましょう🥹
